add sandbox plugin
manytask/checker pull request #79
Opened 2023-12-23 16:46 UTC by dmitriy-lukashevich

## Description

Add plugin for safe execution of students tasks.
For sandbox firejail tool is used.

## Motivation and Context

Related to 
* #
* #
* 

Closes #

## Contribution Checklist

- [ ] I have read and agreed on the [CONTRIBUTING](../CONTRIBUTING.md) and [CODE OF CONDUCT](../CODE_OF_CONDUCT.md) documents.
- [ ] I have run linters, type checks, import sorting and tests locally.
- [ ] I have added comments to code in hard-to-understand areas.
- [ ] I have added 100% coverage tests for the new code (or aren't needed).
- [ ] I have added docs for the new code (or aren't needed).
- [ ] I have used [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) title: `tag(scope): description`. 

## [optional] Screenshots

## [optional] Special notes

## [optional] What gif best describes this PR or how it makes you feel?

2023-12-23 16:49 UTC, dmitriy-lukashevich commented on checker/plugins/scripts.py
> -        env_whitelist: list[str] = Field(default_factory=lambda: ["PATH"])
Кажется, теперь все элементы изолирования должны быть в отдельном плагине.

2023-12-25 07:32 UTC, k4black requested changes

2023-12-25 07:32 UTC, k4black commented on checker/plugins/firejail.py
> +        run_args = RunScriptPlugin.Args(origin=args.origin, script=' '.join(command), timeout=args.timeout)
No need to join command, Script plugin (subprocess inside) accepts list

2023-12-25 07:32 UTC, k4black commented on checker/plugins/firejail.py
> +    Args = RunScriptPlugin.Args
Seems it’s better to make custom Args - you need env whitelist, potentially network mode (eg for pip install profile or socket access) , custom allowed dirs -all with default parameters

2023-12-25 07:32 UTC, k4black commented on checker/plugins/firejail.py
> +                   ]
Apply black for styling

2023-12-25 07:32 UTC, k4black commented on checker/plugins/firejail.py
> +                   f'{PYTHONPATH}={os.environ.get(PYTHONPATH, "")}',
Potential untrusted code execution if spaces in the ENV. Seeems we need to secure with “” and or backslash all env content

2023-12-25 07:32 UTC, k4black commented on checker/plugins/firejail.py
> +    """Plugin for running scripts in safe mode."""
Could you please elaborate a little explaining use of firejail

2023-12-25 07:32 UTC, k4black commented on checker/plugins/firejail.py
> +    def _run(self, args: Args, *, verbose: bool = False) -> str:
Seems the problem we faced in tests can be tackled here - you need to check jirejail exists and through clear error msg

2023-12-27 17:11 UTC, closed without merging

2023-12-27 17:12 UTC, k4black commented
пересоздай пожалуйста в main